name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'

      - name: Install dependencies
        run: go get ./...

      - name: echo1
        run: ls -lh

      - name: Build
        run: go build -C ./cmd/openapi-cli -ldflags '-w -s'

      - name: echo2
        run: ls -lh

      - name: echo3
        run: echo "ls -lh ./cmd/openapi-cli"

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag openapi-cli:$(date +%s)
